#+TITLE: InCens: Information transfer in Central Dogma systems

InCens contains python3 scripts and jupyter notebooks to compute the ideal and the protein-level channel capacity for central dogma reaction networks. The documentation is available at, https://incens.readthedocs.io/en/latest/.

* System Requirements

** Hardware requirements
   ~InCens~ was primarily developed and used on a Mac Mini with 16 GB RAM, but should work on most other computers too. The stochastic simulations can take a long time, but they do not use a large amount of storage.

** Software requirements
   ~InCens~ is supported for macOS and has not been tested for other systems yet.

** Python Dependencies
   ~InCens~ needs the following libraries:
   - ~pandas~
   - ~numpy~
   - ~scipy~

* Package content

Notebook for computing the ideal channel capacity is, Computation_of_ideal_channel_capacity.ipynb.

Notebook for performing Gillespie (kinetic Monte Carlo) simulation of central dogma reactions is, Central_dogma_simulator.ipynb.

Notebook for plotting the distribution of integration times for the four species is, Integration_time_of_species.ipynb.

The transcript and protein half-lives for the four species are in folder ./half-lives.

The central dogma rate constants for the four species are in ./scripts/simulation_data.py.

Please cite the following preprint if you are using this code.

Sarkar, S., & Rammohan, J. (2022). Nearly maximal information gain due to time integration in central dogma reactions. bioRxiv.
